apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pv
  namespace: my-namespace
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/grafana-pv