apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
  namespace: database
spec:
  capacity:
    storage: 2Gi  
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /root/mongo-data 
