apiVersion: v1
kind: PersistentVolume
metadata:
  name: portainer-pv
spec:
  capacity:
    storage: 24Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: generic  
  hostPath:
    path: /root/portainer
