apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: accs2023/proiect_idp_auth:latest
        ports:
        - containerPort: 4002