apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  namespace: appservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: business-service
  template:
    metadata:
      labels:
        app: business-service
    spec:
      containers:
      - name: business-service
        image: cgrigore0410/business-svc:latest 
        ports:
        - containerPort: 6000
