apiVersion: apps/v1
kind: Deployment
metadata:
  name: kong
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kong
  template:
    metadata:
      labels:
        app: kong
    spec:
      containers:
      - name: kong
        image: kong:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: kong-config
          mountPath: /usr/local/kong/declarative/kong.yml
          subPath: kong.yml
        env:
        - name: KONG_DATABASE
          value: 'off'
        - name: KONG_DECLARATIVE_CONFIG
          value: /usr/local/kong/declarative/kong.yml
        - name: KONG_PROXY_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_ADMIN_ACCESS_LOG
          value: /dev/stdout
        - name: KONG_PROXY_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_ERROR_LOG
          value: /dev/stderr
        - name: KONG_ADMIN_LISTEN
          value: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      volumes:
      - name: kong-config
        configMap:
          name: kong-configmap
