apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
      - name: mongo
        image: mongo:4.4.18
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
        - name: mongo-init-script
          mountPath: /docker-entrypoint-initdb.d/mongo-init.js
          subPath: mongo-init.js
      volumes:
      - name: mongo-data
        persistentVolumeClaim:
            claimName: mongo-pvc 
      - name: mongo-init-script
        configMap:
           name: mongo-init-config
