apiVersion: v1
kind: Service
metadata:
  name: kong
  namespace: monitoring
spec:
  type: NodePort
  ports:
  - name: proxy
    port: 80
    targetPort: 8000
    nodePort: 30080
  selector:
    app: kong
